#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'shaderapigl'

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'SHADER_DLL_EXPORT',
		'PROTECTED_THINGS_ENABLE',
		'strncpy=use_Q_strncpy_instead',
		'_snprintf=use_Q_snprintf_instead',
	])

def build(bld):
	source = [
		'shaderapigl.cpp',
		'../../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common',
		'../'
	] + bld.env.INCLUDES_SDL2

	defines = []
	libs = ['tier0', 'tier1', 'vstdlib', 'bitmap', 'tier2', 'mathlib']
	linkflags = []

	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT', 'SDL2']
		linkflags += ['-lGLESv3', '-lEGL']
	elif bld.env.DEST_OS == 'win32':
		libs += ['OPENGL32']
	else:
		libs += ['GL', 'SDL2']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		linkflags = linkflags,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
