struct PCServerClassInfo_t
{
	const char *m_pClassName;
	const char *m_pDatatableName;
};

static const PCServerClassInfo_t s_PCServerClasses[197] =
{
	{ "CAI_BaseNPC", "DT_AI_BaseNPC" }, // 0
	{ "CAK47", "DT_WeaponAK47" }, // 1
	{ "CBaseAnimating", "DT_BaseAnimating" }, // 2
	{ "CBaseAnimatingOverlay", "DT_BaseAnimatingOverlay" }, // 3
	{ "CBaseCombatCharacter", "DT_BaseCombatCharacter" }, // 4
	{ "CBaseCombatWeapon", "DT_BaseCombatWeapon" }, // 5
	{ "CBaseCSGrenade", "DT_BaseCSGrenade" }, // 6
	{ "CBaseCSGrenadeProjectile", "DT_BaseCSGrenadeProjectile" }, // 7
	{ "CBaseDoor", "DT_BaseDoor" }, // 8
	{ "CBaseEntity", "DT_BaseEntity" }, // 9
	{ "CBaseFlex", "DT_BaseFlex" }, // 10
	{ "CBaseGrenade", "DT_BaseGrenade" }, // 11
	{ "CBaseParticleEntity", "DT_BaseParticleEntity" }, // 12
	{ "CBasePlayer", "DT_BasePlayer" }, // 13
	{ "CBaseProjectile", "DT_BaseProjectile" }, // 14
	{ "CBasePropDoor", "DT_BasePropDoor" }, // 15
	{ "CBaseTeamObjectiveResource", "DT_BaseTeamObjectiveResource" }, // 16
	{ "CBaseTempEntity", "DT_BaseTempEntity" }, // 17
	{ "CBaseViewModel", "DT_BaseViewModel" }, // 18
	{ "CBeam", "DT_Beam" }, // 19
	{ "CBoneFollower", "DT_BoneFollower" }, // 20
	{ "CBreakableProp", "DT_BreakableProp" }, // 21
	{ "CBreakableSurface", "DT_BreakableSurface" }, // 22
	{ "CC4", "DT_WeaponC4" }, // 23
	{ "CColorCorrection", "DT_ColorCorrection" }, // 24
	{ "CColorCorrectionVolume", "DT_ColorCorrectionVolume" }, // 25
	{ "CCSGameRulesProxy", "DT_CSGameRulesProxy" }, // 26
	{ "CCSPlayer", "DT_CSPlayer" }, // 27
	{ "CCSPlayerResource", "DT_CSPlayerResource" }, // 28
	{ "CCSRagdoll", "DT_CSRagdoll" }, // 29
	{ "CCSTeam", "DT_CSTeam" }, // 30
	{ "CDEagle", "DT_WeaponDEagle" }, // 31
	{ "CDynamicLight", "DT_DynamicLight" }, // 32
	{ "CDynamicProp", "DT_DynamicProp" }, // 33
	{ "CEmbers", "DT_Embers" }, // 34
	{ "CEntityDissolve", "DT_EntityDissolve" }, // 35
	{ "CEntityFlame", "DT_EntityFlame" }, // 36
	{ "CEntityParticleTrail", "DT_EntityParticleTrail" }, // 37
	{ "CEnvDetailController", "DT_DetailController" }, // 38
	{ "CEnvParticleScript", "DT_EnvParticleScript" }, // 39
	{ "CEnvProjectedTexture", "DT_EnvProjectedTexture" }, // 40
	{ "CEnvQuadraticBeam", "DT_QuadraticBeam" }, // 41
	{ "CEnvScreenEffect", "DT_EnvScreenEffect" }, // 42
	{ "CEnvScreenOverlay", "DT_EnvScreenOverlay" }, // 43
	{ "CEnvTonemapController", "DT_EnvTonemapController" }, // 44
	{ "CEnvWind", "DT_EnvWind" }, // 45
	{ "CFireSmoke", "DT_FireSmoke" }, // 46
	{ "CFireTrail", "DT_FireTrail" }, // 47
	{ "CFish", "DT_CFish" }, // 48
	{ "CFlashbang", "DT_Flashbang" }, // 49
	{ "CFogController", "DT_FogController" }, // 50
	{ "CFootstepControl", "DT_FootstepControl" }, // 51
	{ "CFunc_Dust", "DT_Func_Dust" }, // 52
	{ "CFunc_LOD", "DT_Func_LOD" }, // 53
	{ "CFuncAreaPortalWindow", "DT_FuncAreaPortalWindow" }, // 54
	{ "CFuncConveyor", "DT_FuncConveyor" }, // 55
	{ "CFuncLadder", "DT_FuncLadder" }, // 56
	{ "CFuncMonitor", "DT_FuncMonitor" }, // 57
	{ "CFuncOccluder", "DT_FuncOccluder" }, // 58
	{ "CFuncReflectiveGlass", "DT_FuncReflectiveGlass" }, // 59
	{ "CFuncRotating", "DT_FuncRotating" }, // 60
	{ "CFuncSmokeVolume", "DT_FuncSmokeVolume" }, // 61
	{ "CFuncTrackTrain", "DT_FuncTrackTrain" }, // 62
	{ "CGameRulesProxy", "DT_GameRulesProxy" }, // 63
	{ "CHandleTest", "DT_HandleTest" }, // 64
	{ "CHEGrenade", "DT_HEGrenade" }, // 65
	{ "CHostage", "DT_CHostage" }, // 66
	{ "CInfoLadderDismount", "DT_InfoLadderDismount" }, // 67
	{ "CInfoLightingRelative", "DT_InfoLightingRelative" }, // 68
	{ "CInfoOverlayAccessor", "DT_InfoOverlayAccessor" }, // 69
	{ "CKnife", "DT_WeaponKnife" }, // 70
	{ "CLightGlow", "DT_LightGlow" }, // 71
	{ "CMaterialModifyControl", "DT_MaterialModifyControl" }, // 72
	{ "CParticleFire", "DT_ParticleFire" }, // 73
	{ "CParticlePerformanceMonitor", "DT_ParticlePerformanceMonitor" }, // 74
	{ "CParticleSystem", "DT_ParticleSystem" }, // 75
	{ "CPhysBox", "DT_PhysBox" }, // 76
	{ "CPhysBoxMultiplayer", "DT_PhysBoxMultiplayer" }, // 77
	{ "CPhysicsProp", "DT_PhysicsProp" }, // 78
	{ "CPhysicsPropMultiplayer", "DT_PhysicsPropMultiplayer" }, // 79
	{ "CPhysMagnet", "DT_PhysMagnet" }, // 80
	{ "CPlantedC4", "DT_PlantedC4" }, // 81
	{ "CPlasma", "DT_Plasma" }, // 82
	{ "CPlayerResource", "DT_PlayerResource" }, // 83
	{ "CPointCamera", "DT_PointCamera" }, // 84
	{ "CPointCommentaryNode", "DT_PointCommentaryNode" }, // 85
	{ "CPointWorldText", "DT_PointWorldText" }, // 86
	{ "CPoseController", "DT_PoseController" }, // 87
	{ "CPrecipitation", "DT_Precipitation" }, // 88
	{ "CPredictedViewModel", "DT_PredictedViewModel" }, // 89
	{ "CPropJeep", "DT_PropJeep" }, // 90
	{ "CPropVehicleDriveable", "DT_PropVehicleDriveable" }, // 91
	{ "CRagdollManager", "DT_RagdollManager" }, // 92
	{ "CRagdollProp", "DT_Ragdoll" }, // 93
	{ "CRagdollPropAttached", "DT_Ragdoll_Attached" }, // 94
	{ "CRopeKeyframe", "DT_RopeKeyframe" }, // 95
	{ "CSceneEntity", "DT_SceneEntity" }, // 96
	{ "CShadowControl", "DT_ShadowControl" }, // 97
	{ "CSlideshowDisplay", "DT_SlideshowDisplay" }, // 98
	{ "CSmokeGrenade", "DT_SmokeGrenade" }, // 99
	{ "CSmokeStack", "DT_SmokeStack" }, // 100
	{ "CSpotlightEnd", "DT_SpotlightEnd" }, // 101
	{ "CSprite", "DT_Sprite" }, // 102
	{ "CSpriteOriented", "DT_SpriteOriented" }, // 103
	{ "CSpriteTrail", "DT_SpriteTrail" }, // 104
	{ "CSteamJet", "DT_SteamJet" }, // 105
	{ "CSun", "DT_Sun" }, // 106
	{ "CTeam", "DT_Team" }, // 107
	{ "CTeamplayRoundBasedRulesProxy", "DT_TeamplayRoundBasedRulesProxy" }, // 108
	{ "CTEArmorRicochet", "DT_TEArmorRicochet" }, // 109
	{ "CTEBaseBeam", "DT_BaseBeam" }, // 110
	{ "CTEBeamEntPoint", "DT_TEBeamEntPoint" }, // 111
	{ "CTEBeamEnts", "DT_TEBeamEnts" }, // 112
	{ "CTEBeamFollow", "DT_TEBeamFollow" }, // 113
	{ "CTEBeamLaser", "DT_TEBeamLaser" }, // 114
	{ "CTEBeamPoints", "DT_TEBeamPoints" }, // 115
	{ "CTEBeamRing", "DT_TEBeamRing" }, // 116
	{ "CTEBeamRingPoint", "DT_TEBeamRingPoint" }, // 117
	{ "CTEBeamSpline", "DT_TEBeamSpline" }, // 118
	{ "CTEBloodSprite", "DT_TEBloodSprite" }, // 119
	{ "CTEBloodStream", "DT_TEBloodStream" }, // 120
	{ "CTEBreakModel", "DT_TEBreakModel" }, // 121
	{ "CTEBSPDecal", "DT_TEBSPDecal" }, // 122
	{ "CTEBubbles", "DT_TEBubbles" }, // 123
	{ "CTEBubbleTrail", "DT_TEBubbleTrail" }, // 124
	{ "CTEClientProjectile", "DT_TEClientProjectile" }, // 125
	{ "CTEDecal", "DT_TEDecal" }, // 126
	{ "CTEDust", "DT_TEDust" }, // 127
	{ "CTEDynamicLight", "DT_TEDynamicLight" }, // 128
	{ "CTEEffectDispatch", "DT_TEEffectDispatch" }, // 129
	{ "CTEEnergySplash", "DT_TEEnergySplash" }, // 130
	{ "CTEExplosion", "DT_TEExplosion" }, // 131
	{ "CTEFireBullets", "DT_TEFireBullets" }, // 132
	{ "CTEFizz", "DT_TEFizz" }, // 133
	{ "CTEFootprintDecal", "DT_TEFootprintDecal" }, // 134
	{ "CTEGaussExplosion", "DT_TEGaussExplosion" }, // 135
	{ "CTEGlowSprite", "DT_TEGlowSprite" }, // 136
	{ "CTEImpact", "DT_TEImpact" }, // 137
	{ "CTEKillPlayerAttachments", "DT_TEKillPlayerAttachments" }, // 138
	{ "CTELargeFunnel", "DT_TELargeFunnel" }, // 139
	{ "CTEMetalSparks", "DT_TEMetalSparks" }, // 140
	{ "CTEMuzzleFlash", "DT_TEMuzzleFlash" }, // 141
	{ "CTEParticleSystem", "DT_TEParticleSystem" }, // 142
	{ "CTEPhysicsProp", "DT_TEPhysicsProp" }, // 143
	{ "CTEPlantBomb", "DT_TEPlantBomb" }, // 144
	{ "CTEPlayerAnimEvent", "DT_TEPlayerAnimEvent" }, // 145
	{ "CTEPlayerDecal", "DT_TEPlayerDecal" }, // 146
	{ "CTEProjectedDecal", "DT_TEProjectedDecal" }, // 147
	{ "CTERadioIcon", "DT_TERadioIcon" }, // 148
	{ "CTEShatterSurface", "DT_TEShatterSurface" }, // 149
	{ "CTEShowLine", "DT_TEShowLine" }, // 150
	{ "CTesla", "DT_Tesla" }, // 151
	{ "CTESmoke", "DT_TESmoke" }, // 152
	{ "CTESparks", "DT_TESparks" }, // 153
	{ "CTESprite", "DT_TESprite" }, // 154
	{ "CTESpriteSpray", "DT_TESpriteSpray" }, // 155
	{ "CTest_ProxyToggle_Networkable", "DT_ProxyToggle" }, // 156
	{ "CTestTraceline", "DT_TestTraceline" }, // 157
	{ "CTEWorldDecal", "DT_TEWorldDecal" }, // 158
	{ "CVGuiScreen", "DT_VGuiScreen" }, // 159
	{ "CVoteController", "DT_VoteController" }, // 160
	{ "CWaterBullet", "DT_WaterBullet" }, // 161
	{ "CWaterLODControl", "DT_WaterLODControl" }, // 162
	{ "CWeaponAug", "DT_WeaponAug" }, // 163
	{ "CWeaponAWP", "DT_WeaponAWP" }, // 164
	{ "CWeaponCSBase", "DT_WeaponCSBase" }, // 165
	{ "CWeaponCSBaseGun", "DT_WeaponCSBaseGun" }, // 166
	{ "CWeaponCycler", "DT_WeaponCycler" }, // 167
	{ "CWeaponElite", "DT_WeaponElite" }, // 168
	{ "CWeaponFamas", "DT_WeaponFamas" }, // 169
	{ "CWeaponFiveSeven", "DT_WeaponFiveSeven" }, // 170
	{ "CWeaponG3SG1", "DT_WeaponG3SG1" }, // 171
	{ "CWeaponGalil", "DT_WeaponGalil" }, // 172
	{ "CWeaponGlock", "DT_WeaponGlock" }, // 173
	{ "CWeaponM249", "DT_WeaponM249" }, // 174
	{ "CWeaponM3", "DT_WeaponM3" }, // 175
	{ "CWeaponM4A1", "DT_WeaponM4A1" }, // 176
	{ "CWeaponMAC10", "DT_WeaponMAC10" }, // 177
	{ "CWeaponMP5Navy", "DT_WeaponMP5Navy" }, // 178
	{ "CWeaponP228", "DT_WeaponP228" }, // 179
	{ "CWeaponP90", "DT_WeaponP90" }, // 180
	{ "CWeaponScout", "DT_WeaponScout" }, // 181
	{ "CWeaponSG550", "DT_WeaponSG550" }, // 182
	{ "CWeaponSG552", "DT_WeaponSG552" }, // 183
	{ "CWeaponTMP", "DT_WeaponTMP" }, // 184
	{ "CWeaponUMP45", "DT_WeaponUMP45" }, // 185
	{ "CWeaponUSP", "DT_WeaponUSP" }, // 186
	{ "CWeaponXM1014", "DT_WeaponXM1014" }, // 187
	{ "CWorld", "DT_WORLD" }, // 188
	{ "DustTrail", "DT_DustTrail" }, // 189
	{ "MovieExplosion", "DT_MovieExplosion" }, // 190
	{ "NextBotCombatCharacter", "DT_NextBot" }, // 191
	{ "ParticleSmokeGrenade", "DT_ParticleSmokeGrenade" }, // 192
	{ "RocketTrail", "DT_RocketTrail" }, // 193
	{ "SmokeTrail", "DT_SmokeTrail" }, // 194
	{ "SporeExplosion", "DT_SporeExplosion" }, // 195
	{ "SporeTrail", "DT_SporeTrail" }, // 196
};