//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Purpose: 
//
// $NoKeywords: $
//=============================================================================//

#include <stdlib.h>
#include <string.h>
#include "materialsystem/imaterialproxy.h"
#include "materialproxyfactory.h"
#include "toolframework/itoolframework.h"
#include "toolframework/itoolsystem.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"
extern CSysModule		*g_ClientDLLModule;

IMaterialProxy *CMaterialProxyFactory::CreateProxy( const char *proxyName )
{
#if !defined(SWDS)
	IMaterialProxy *materialProxy = LookupProxy( proxyName, Sys_GetFactory( g_ClientDLLModule ) );

	// If the client didn't have it and we're in tool mode, ask the tools...
	if ( toolframework->InToolMode() && !materialProxy )
	{
		materialProxy = toolframework->LookupProxy( proxyName );
	}

	if( !materialProxy )
	{
		ConDMsg( "Can't find material proxy \"%s\"\n", proxyName );
		return NULL;
	}
	return materialProxy;
#else
	return NULL;
#endif
}

void CMaterialProxyFactory::DeleteProxy( IMaterialProxy *pProxy )
{
	// how do you delete something generated by an interface.h factory?
	if( pProxy )
	{
		pProxy->Release();
	}
}


//-----------------------------------------------------------------------------
// Look up proxy
//-----------------------------------------------------------------------------
IMaterialProxy *CMaterialProxyFactory::LookupProxy( const char *proxyName, CreateInterfaceFn factory )
{
	if( !factory )
		return NULL;

	char proxyVersionedName[256];
	if(!proxyName || Q_strlen(proxyName)+Q_strlen(IMATERIAL_PROXY_INTERFACE_VERSION)>=sizeof(proxyVersionedName)) return NULL;
	Q_snprintf(proxyVersionedName,sizeof(proxyVersionedName),"%s%s",proxyName,IMATERIAL_PROXY_INTERFACE_VERSION);
	IMaterialProxy *proxy=(IMaterialProxy *)factory(proxyVersionedName,NULL);
	if(proxy) return proxy;
	// Some ported map VMTs lower-case names. Interface factories are case
	// sensitive even though material keys are not. Resolve built-in spellings.
	static const char *names[]={"LinearRamp","TextureTransform","AnimatedTexture","TextureScroll",
		"Sine","Equals","Add","Subtract","Multiply","Divide","Clamp","Abs","LessOrEqual",
		"SelectFirstIfNonZero","GaussianNoise","UniformNoise","CurrentTime","PlayerProximity",
		"EntityRandom","PlayerSpeed","PlayerPosition","EntityOrigin","EntityVelocity","EntityAngles",
		"WorldDims","TextureToggle","WaterLOD","TeamColor","IronSightAmount"};
	for(int i=0;i<ARRAYSIZE(names);++i) if(!Q_stricmp(proxyName,names[i]))
	{
		Q_snprintf(proxyVersionedName,sizeof(proxyVersionedName),"%s%s",names[i],IMATERIAL_PROXY_INTERFACE_VERSION);
		return (IMaterialProxy *)factory(proxyVersionedName,NULL);
	}
	return NULL;
}



