#! /usr/bin/env python
# encoding: utf-8

PROJECT_NAME = 'cstriketest'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = ['cstriketest.cpp', 'cstrike_gameplay_tests.cpp', 'cstrike_interaction_tests.cpp']
	includes = ['../../public', '../../public/tier0', '../../game/shared']
	libs = ['tier0', 'tier1', 'unitlib']

	if bld.env.DEST_OS != 'win32':
		libs += ['DL', 'LOG']
	else:
		libs += ['USER32', 'SHELL32']

	bld.shlib(
		source = source,
		target = PROJECT_NAME,
		name = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		use = libs,
		install_path = bld.env.TESTDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
